'''
configuration of server.py program on Raspberry
'''

PORT = 5000
VIDEO_ARCHIVE = "static/video_archive"

DEFAULT_PICTURE_WIDTH = 1280
DEFAULT_PICTURE_HEIGHT = 720
DEFAULT_VIDEO_DURATION = 10 # seconds
DEFAULT_FPS = 10
DEFAULT_VIDEO_WIDTH = 1280
DEFAULT_VIDEO_HEIGHT = 720
DEFAULT_VIDEO_QUALITY = 1 # Mb/s

LOG_PATH = "server.log"

WIFI_INTERFACE = "wlp2s0"